var events = [
{
"Title": "Collaborative Piano",
"Description": "Event Url http://calendar.byui.edu/EventDetails.aspx?data=hHr80o3M7J56RPvxI0fd9gyhe6%2fZqWpvQIY4DiVzpUXRCHuJXXKtr07n%2bBhGwihb",
"StartTime": "18:00:00",
"EndTime": "19:30:00",
"Date": "2015-04-03",
"Price": "null",
"Picture": "img\/BYU-Idaho_Medallion_Logo.png",
"Location": "Snow 269 Recital Hall",
"Email": null},
{
"Title": "Breakdance Workshop",
"Description": "Learn how to Breakdance at this weekly, free workshop taught by BYU-Idaho students.  All are welcome! Event Url http://calendar.byui.edu/EventDetails.aspx?data=hHr80o3M7J7TUiiBg2RnzZ7FuAbi9yjMD6YC21w07j1vsHsxusDIteYPHZcPoa7O",
"StartTime": "19:00:00",
"EndTime": "20:00:00",
"Date": "2015-04-03",
"Price": "null",
"Picture": "img\/BYU-Idaho_Medallion_Logo.png",
"Location": "Hart 234 Dance Studio",
"Email": null},
{
"Title": "Chamber Brass",
"Description": "Event Url http://calendar.byui.edu/EventDetails.aspx?data=hHr80o3M7J6Ik8vq%2ba3OHctpdTj7bovwRGQ1v5HWzklnj%2bVQvKYTgTOpjPd9KSgl",
"StartTime": "19:30:00",
"EndTime": "20:30:00",
"Date": "2015-04-03",
"Price": "null",
"Picture": "img\/BYU-Idaho_Medallion_Logo.png",
"Location": "Snow 136 Barrus Concert Hall",
"Email": null},
{
"Title": "Ballroom Dancing",
"Description": "The weekly ballroom dance is a chance to meet people while learning various dances. The ballroom dance covers a variety of different dancing styles including international Latin and standard. Instruction is offered for the first hour, and instructors are available for individual help throughout the dance. Event Url http://calendar.byui.edu/EventDetails.aspx?data=hHr80o3M7J4PwyxXSNP49mXUWYQYs",
"StartTime": "20:00:00",
"EndTime": "23:00:00",
"Date": "2015-04-03",
"Price": "null",
"Picture": "img\/BYU-Idaho_Medallion_Logo.png",
"Location": "Hinckley 260/270 Gym",
"Email": null},
{
"Title": "General Conference",
"Description": "Event Url http://calendar.byui.edu/EventDetails.aspx?data=hHr80o3M7J6KAJTl47%2b4YbK3wX8X1OpOzcgpikS4cfNOJp6dGw9WkQMXUn1eJc4m",
"StartTime": "10:00:00",
"EndTime": "00:00:00",
"Date": "2015-04-04",
"Price": "null",
"Picture": "img\/BYU-Idaho_Medallion_Logo.png",
"Location": "Taylor Chapel/Cultural Hall",
"Email": null},
{
"Title": "Fencing",
"Description": "Fencing is the martial art of fighting with blades. The common version of fencing today, generally known as olympic fencing, is divided into three weapon categories: foil, sabre (spelled saber in the United States) and ?p?e. Classical fencing uses the same weapons, but approaches fencing as a martial art. Competitive fencing is one of five activities which have been featured in every one of the mo",
"StartTime": "13:00:00",
"EndTime": "15:00:00",
"Date": "2015-04-04",
"Price": "null",
"Picture": "img\/BYU-Idaho_Medallion_Logo.png",
"Location": "Hart 141 Classroom - Clogging Studio",
"Email": null},
{
"Title": "General Conference",
"Description": "Event Url http://calendar.byui.edu/EventDetails.aspx?data=hHr80o3M7J6KAJTl47%2b4YbK3wX8X1OpOzcgpikS4cfPrBtSvOs%2b1NCgi6XZiPSEW",
"StartTime": "14:00:00",
"EndTime": "16:00:00",
"Date": "2015-04-04",
"Price": "null",
"Picture": "img\/BYU-Idaho_Medallion_Logo.png",
"Location": "Taylor Chapel/Cultural Hall",
"Email": null},
{
"Title": "General Conference - Priesthood Session",
"Description": "Event Url http://calendar.byui.edu/EventDetails.aspx?data=hHr80o3M7J6KAJTl47%2b4YbK3wX8X1OpOzcgpikS4cfPyEaF5ce3BSvsxtirN3j7K",
"StartTime": "18:00:00",
"EndTime": "20:00:00",
"Date": "2015-04-04",
"Price": "null",
"Picture": "img\/BYU-Idaho_Medallion_Logo.png",
"Location": "BYU-Idaho Center Auditorium",
"Email": null},
{
"Title": "General Conference",
"Description": "Event Url http://calendar.byui.edu/EventDetails.aspx?data=hHr80o3M7J6KAJTl47%2b4YbK3wX8X1OpOCXuFYc5GMv4Qff7O66xPqz4NQeWU4NWP",
"StartTime": "10:00:00",
"EndTime": "00:00:00",
"Date": "2015-04-05",
"Price": "null",
"Picture": "img\/BYU-Idaho_Medallion_Logo.png",
"Location": "Taylor Chapel/Cultural Hall",
"Email": null},
{
"Title": "test",
"Description": "456",
"StartTime": "19:00:00",
"EndTime": "20:00:00",
"Date": "2015-09-30",
"Price": "null",
"Picture": "img\/BYU-Idaho_Medallion_Logo.png",
"Location": "3455",
"Email": null},
{
"Title": "test",
"Description": "456",
"StartTime": "19:00:00",
"EndTime": "20:00:00",
"Date": "2015-09-30",
"Price": "null",
"Picture": "img\/BYU-Idaho_Medallion_Logo.png",
"Location": "3455",
"Email": null},
{
"Title": "test",
"Description": "456",
"StartTime": "19:00:00",
"EndTime": "20:00:00",
"Date": "2015-09-30",
"Price": "null",
"Picture": "img\/BYU-Idaho_Medallion_Logo.png",
"Location": "3455",
"Email": null},
{
"Title": "hi",
"Description": "kahild dfweo6bawe 74287y",
"StartTime": "19:00:00",
"EndTime": "20:00:00",
"Date": "2015-04-06",
"Price": "null",
"Picture": "img\/BYU-Idaho_Medallion_Logo.png",
"Location": "Para;ibdiuhbfvowaev",
"Email": null},
{
"Title": "hi",
"Description": "SDvarstn54u thg",
"StartTime": "19:00:00",
"EndTime": "20:00:00",
"Date": "2015-04-06",
"Price": "null",
"Picture": "img\/BYU-Idaho_Medallion_Logo.png",
"Location": "sadfb n647mn3s 6ueht",
"Email": null},
{
"Title": "Doneljnl",
"Description": "SDvarstn54u thg",
"StartTime": "19:00:00",
"EndTime": "20:00:00",
"Date": "2015-04-06",
"Price": "null",
"Picture": "img\/BYU-Idaho_Medallion_Logo.png",
"Location": "sadfb n647mn3s 6ueht",
"Email": null},
{
"Title": "testdonefg",
"Description": "sdlfk",
"StartTime": "19:00:00",
"EndTime": "20:00:00",
"Date": "2015-04-06",
"Price": "3.00",
"Picture": "img\/BYU-Idaho_Medallion_Logo.png",
"Location": "aldjf",
"Email": null},
];